# -*- coding: utf-8 -*-
##############################################################################
#
#    OpenERP, Open Source Management Solution
#    Copyright (C) 2004-2010 Tiny SPRL (<http://tiny.be>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
# Generated by the Odoo plugin for Dia !
from openerp import models, fields, api


class ig_base_dependencia_iglesia(models.Model):
    """Estructura de Dependencias de Iglesia. Esto debe estar en el módulo base de IG"""
    _name = 'ig.base.dependencia_iglesia'
    #_rec_name = ''
    codigo = fields.Char("Código", size=20, help='Código de la Dependencia')
    tipo = fields.Selection([('conbertura','Cobertura'),('visitante','Visitante'),('aliada','Aliada')], string="Tipo de Iglesia", help='Tipo de Iglesia')
    nombre = fields.Char(string="Nombre", size=60)
    ubicacion = fields.Text(string="Ubicación", help='Ubicación física de la gerencia')
    direccion = fields.Text(size=150, help='Dirección de la Iglesia')
    miembro_id = fields.Many2one('ig.base.dependecia_iglesia', string="miembro", help='miembro a la que pertenece')


class ig_base_dependencia_ministerio(models.Model):
    """Estructura de Dependencias Ministeriales. Esto debe estar en el módulo base de iglesia"""
    _name = 'ig.base.dependencia_ministerio'
    #_rec_name = ''
    codigo = fields.Char(string="Código", size=10, help='Código del Ministerio')
    nombre = fields.Char(string="Nombre", size=60, help='Nombre de la Ministerio')
    ubicacion = fields.Text(string="Ubicación", help='Ubicación física de la Ministerio')
    ministerio_id = fields.Many2one('ig.base.dependencia_iglesia', string="Iglesia", help='Ministerio que pertenecen a la iglesia')
    lider_ministerio = fields.Char(string= "Lider de ministerio", size = 60, help='Nombre del Lider de Celula')


class ig_base_dependencia_celula(models.Model):
    """Estructura de Dependencias Celula. Esto debe estar en el módulo base de iglesia"""
    _name = 'ig.base.dependencia_celula'
    #_rec_name = ''
    codigo = fields.Char(string="Código", size=10, help='Código del Ministerio')
    nombre = fields.Char(string="Nombre", size=60, help='Nombre de la Ministerio')
    ubicacion = fields.Text(string="Ubicación", help='Ubicación física de la Ministerio')
    celula_id = fields.Many2one('ig.base.dependencia_iglesia', string="Iglesia", help='Celula que pertenecen a la iglesia')
    lider_celula = fields.Many2one('ig.master.iglesia.miembros', string="Lider de celula", help='Nombre del Lider de Celula')
    miembro_id = fields.Many2many('ig.iglesia.miembros', string = "miembros de celula")
    anfitrion = fields.Many2one('ig.master.iglesia.miembros', string="Anfitrion de celula", help='Anfitrion de la casa')
    ayudante = fields.Many2one('ig.master.iglesia.miembros', string="ayudante de celula")
    invitados = fields.Text(string="invitados a la celula")


class ig_base_dependencia_comision(models.Model):
    """Estructura de Dependencias Comision. Esto debe estar en el módulo base de iglesia"""
    _name = 'ig.base.dependencia_comision'
    #_rec_name = ''
    codigo = fields.Char(string="Código", size=10, help='Código del Ministerio')
    nombre = fields.Char(string="Nombre", size=60, help='Nombre de la Ministerio')
    ubicacion = fields.Text(string="Ubicación", help='Ubicación física de la Ministerio')
    comision_id = fields.Many2one('ig.base.dependencia_iglesia', string="Iglesia", help='Comision que pertenecen a la iglesia')
    lider_ministerio = fields.Char(string= "Lider de ministerio", size = 60, help='Nombre del Lider de Celula')


class ig_iglesia_estudios_teologicos(models.Model):
    _name = 'ig.iglesia.estudios_teologicos'
    #_rec_name = ''
    miembro_id = fields.Many2one('ig.miembros', string="Miembros", help='Nombre Completo del miembro de la Iglesia')
    inste = fields.Selection([('libro nro 1','Libro Nro 1'),('libro nro 2','Libro Nro 2'),('libro nro 3','Libro Nro 3'),('libro nro 4','Libro Nro 4')], string="INSTE")
    observacion = fields.Text(string="Observaciones", help='Observaciones del Estudio')
    teologia_universitaria = fields.Selection([('t.s.u.','T.S.U.'),('licenciado','Licenciado'),('doctorado','Doctorado'),('maestria','Maestria')], string="Teologia Universitaria ", help='Estudios Teologicos Universitario')
    escuela_obrero = fields.Selection([('libro nro 1','Libro Nro 1'),('libro nro 2','Libro Nro 2'),('libro nro 3','Libro Nro 3')], string="Escuela de Obrero")
    discipulado = fields.Selection([('libro nro 1','Libro Nro 1'),('libro nro 2','Libro Nro 2'),('libro nro 3','Libro Nro 3'),('libro nro 4','Libro Nro 4')], string="Discipulado")
    otros = fields.Text(string = "Otros Estudios", help='Otros estudios realizado en Teologia')


class ig_iglesia_miembros(models.Model):
    """Registro principal de miembros de la iglesia. Esta clase debe ir en ig.base"""
    _name = 'ig.iglesia.miembros'
    #_rec_name = ''
    cedula = fields.Integer(string="Cédula", help='Cedula de Identidad del Miembro')
    nombres = fields.Char(string="Nombres", size=60, help='Nombres del Miembro')
    apellidos = fields.Char(string="Apellidos", size=60, help='Apellidos del Miembro')
    cargo_ministerial = fields.Selection([('maestro','Maestro'),('evangelista','evangelista'),('lider','Lider'),('pastor','Pastor'),('apostol','Apostol')], string="Cargo en Ministerio", help='Cargo del Miembro')
    dependencia_ministerio_id = fields.Many2one('ig.base.dependencia_ministerio', string="Ministerio", help='Ministerio a la que pertenece el miembro')
    dependencia_comision_id = fields.Many2one('ig.base.dependencia_comision', string="Comision", help='Comision a la que pertenece el miembro')
    dependencia_celula_id = fields.Many2one('ig.base.dependencia_celula', string="Celula", help='Celula a la que pertenece el miembro')
    #parentesco_id = fields.Many2one('ig_iglesia_familia', 'parentesco')
    email = fields.Char(string="Correo Electronico", size=100, help='Correo Electrónico del miembro')
    telefono_personal = fields.Integer(string="Teléfono Personal", help='Telefóno Personal del miembro. Ej: 04261231234')
    direccion_habitacion = fields.Char(string="Direccion de Habitacion", size=100)
    direccion_trabajo = fields.Char(string="Direccion del trabajo", size=100)
    telefono_trabajo = fields.Integer(string="Teléfono del trabajo", help='Telefóno del trabajo del miembro. Ej: 02869233333')
    fecha_nac = fields.Date('Date')
    estado_civil = fields.Selection([('soltero','Soltero'),('casado','Casado'),('concubinato','Concubinato'),('viudo','Viudo'),('divorsiado','Divorsiado'),], string="Estado Civil")
    dependencia_iglesia_id = fields.Many2one('ig.base.dependencia_iglesia', string="Iglesia", help='Iglesia a la que pertenece el miembro')


class ig_iglesia_familia(models.Model):
    """Especificación del Nucleo Familiar,. Ej: Padre, Madre, Hijos, Esposos, Abuelos, Nietos, Tios, Primos, Sobrinos."""
    _name = 'ig.iglesia.familia'
    #_rec_name = ''
    codigo = fields.Char('Código', size=10, help='Código de esta área de incidencias')
    nombre = fields.Char('Nombre', size=60, help='Nombre de esta Área de Incidencia')
    #tipo_familia = fields.One2many('ig_iglesia_miembros', 'parentesco_id', string="Familiar en la Iglesia", help='¿Tiene familiar dentro de la iglesia?')
    parentesco = fields.Selection([('padre','Padre'),('madre','Madre'),('hijo','Hijo'),('sobrino','Sobrino'),('tio','Tio'),('abuelo','Abuelo'),('primo','Primo')], string="Escuela de Obrero")


class ig_iglesia_estudios_seculares(models.Model):
    _name = 'ig.iglesia.estudios_seculares'
    #_rec_name = ''
    miembro_id = fields.Many2one('ig.miembros', string="Miembros", help='Nombre Completo del miembro de la Iglesia')
    Primaria = fields.Char(size=60)
    observacion = fields.Text(string="Observaciones", help='Observaciones del Estudio')
    universidad = fields.Selection([('t.s.u.','T.S.U.'),('licenciado','Licenciado'),('doctorado','Doctorado'),('maestria','Maestria')], string="Teologia Universitaria ", help='Estudios Universitario')
    bachillerato = fields.Char(size=60)
    otros_estudios = fields.Text(string = "Otros Estudios", help='Otros estudios realizado en Teologia')


class ig_iglesia_eclesiastico(models.Model):
    _name = 'ig.iglesia.eclesiastico'
    #_rec_name = ''
    miembro_id = fields.Many2one('ig.miembros', string="Miembros", help='Nombre Completo del miembro de la Iglesia')
    bautizo = fields.Selection([('agua','agua'),('espiritu','Espiritu'),], string="¿Esta bautizado? ")
    observacion = fields.Text(string="Observaciones", help='Observaciones del Estudio')
    creyente = fields.Selection([('si','Si'),('no','No')], string="¿Es creyente? ", help='Estudios Universitario')
    encuentro = fields.Char(size=60, string="¿Asistio a un preencuentro, encuentro o posencuentro? ")
    fecha_conversion = fields.Date('Date', size="¿Cuando se convirtio?")
    lugar_conversion = fields.Text(size=60, string="¿Donde se convirtio?")
    asistencia = fields.Integer(string="¿Cuanto tiempo tiene asistiendo a la iglesia? ")
    fecha_bautizado = fields.Date('Date', string="fecha de bautizo por agua")
    todos_convertidos = fields.Text(string="todos en su familia estan convertidos")


